# conda env export --no-builds > environment.yml
# conda env create -f environment.yml 
name: pmg
channels:
  - defaults
  - anaconda
  # - conda-forge
dependencies:
  - cmake=3.19.6
  - numpy=1.20.2
  - pillow=8.2.0
  - pip=21.1.2
  - python=3.9.5
  - scipy=1.6.2
  - setuptools=52.0.0
  - wheel=0.36.2
  - pyqt=5.9.2
  # - pip:
  #   - -r file:requirements.txt
